version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-12zs3re78f7zc"
s3_prefix = "sam-app"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "PartnerEventSource=\"aws.partner/mongodb.com/stitch.trigger/62adc8ef80a75cebd4314efb\""
image_repositories = []
